

services:
  frontend:
    image: koomespace1/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yolonet

  backend:
    image: koomespace1/backend:latest
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolomy
    networks:
      - yolonet

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - yolonet

networks:
  yolonet:
    driver: bridge

volumes:
  mongodb_data:
