# Stage 1: Build Node.js app
FROM node:13-alpine as build

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend .

# Stage 2: Use Node.js to serve built files
FROM node:13-alpine as production

WORKDIR /app

COPY --from=build /app/build /app/build

EXPOSE 3001

CMD ["node", "server.js"]

