# Stage 1: Build React app
FROM node:13-alpine as build

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client .
RUN npm run build

# Stage 2: Use lightweight HTTP server to serve built files
FROM node:13-alpine as production

WORKDIR /app

COPY --from=build /app/build /app/build

EXPOSE 3000

CMD ["npx", "http-server", "./build", "-p", "3000"]
