---
- name: Remove conflicting packages
  apt:
    name: containerd
    state: absent
  become: true
  tags: docker

- name: Install Docker dependencies
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true
  tags: docker

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags: docker

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes
  become: true
  tags: docker

- name: Debug output for repository list
  command: cat /etc/apt/sources.list.d/docker.list
  register: repo_list
  become: true
  tags: docker

- debug:
    var: repo_list.stdout
  tags: docker

- name: Update apt cache
  apt:
    update_cache: yes
  become: true
  tags: docker

- name: Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true
  tags: docker

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
  become: true
  tags: docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true
  tags: docker
